spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/db
    username: root
    password: 123

api:
  key: ab9b4386c9316ed51c2bc5791651556c
  url-location: http://api.openweathermap.org/geo/1.0/direct?q=
  url-weather: https://api.openweathermap.org/data/2.5/weather

session:
  timelife: 50